### ISSUE TITLE
Can't find cifar10_branchyNet_m.h5

### ISSUE THREAD

**Issue by ad1r20** [swagholikar29/Dynamic-Network-Inference#1]
Hi,

Download everything, installed the packages and when I try to run I get an error sayng [Errno 2] No such file or directory: 'cifar10_branchyNet_m.h5' 

Is there a parameter to set it to train? Thanks

**Comment by swagholikar29** [comment]
Hi,
It's a pretrained model I am using. It's uploaded in the repository now. Using it will solve this issue.
